### ISSUE TITLE
Logs arent enough

### ISSUE THREAD

**Issue by geggleto** [AdamKyle/EvePublicCrest#1]
needs to return JSON and/or XML.

Bonus points for loading things into APC/Memcached/Redis for caching

**Comment by AdamKyle** [comment]
Bonus points if you would like to implement this. :) 

The logs that  I have created are "opinionated" that is it makes assumptions you will use Laravel, assumptions your logs are stored in `storage/logs` and the library also makes assumptions that you will be storing your data and relevant data in a database, in my case I have specific tables that store specific data.

While this is not documented I did not want to lock you in.

**Comment by geggleto** [comment]
Yeah I might try using something that isn't Laravel :P 
seems like crazy overkill.

**Comment by geggleto** [comment]
Actually this would work super well in a Symfony Console App, I think

**Comment by AdamKyle** [comment]
This issue is being closed. Now that I look more into this I see that you are assuming (and please feel free to correct me if I am wrong) that all I do is log out the response that comes back.

That is wrong. I log out the responses yes but I also gather the data and return either containers or decoded JSON that you can then save into a database of your choice.

As of this commit: [4aeca143f91597c2a07297a0c25e7fe95f9dc7d3](https://github.com/AdamKyle/EvePublicCrest/commit/4aeca143f91597c2a07297a0c25e7fe95f9dc7d3) I have vastly improved the README's in places where I felt they were weak in explaining exactly what was going on and how one facade might be related to another.

Should you need more information or something is not clear feel free to ask :)
